#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v12
# autospec commit: fbcebd0
#
Name     : pypi-tokenizers
Version  : 0.19.1
Release  : 8
URL      : https://files.pythonhosted.org/packages/48/04/2071c150f374aab6d5e92aaec38d0f3c368d227dd9e0469a1f0966ac68d1/tokenizers-0.19.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/48/04/2071c150f374aab6d5e92aaec38d0f3c368d227dd9e0469a1f0966ac68d1/tokenizers-0.19.1.tar.gz
Source1  : http://localhost/cgit/vendor/pypi-tokenizers/snapshot/pypi-tokenizers-2024-06-03-18-08-43.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause BSL-1.0 ICU MIT Unicode-DFS-2016 Unlicense
Requires: pypi-tokenizers-license = %{version}-%{release}
Requires: pypi-tokenizers-python = %{version}-%{release}
Requires: pypi-tokenizers-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(maturin)
BuildRequires : pypi(setuptools_rust)
BuildRequires : pypi-maturin
BuildRequires : rustc
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<p align="center">
<br>
<img src="https://huggingface.co/landing/assets/tokenizers/tokenizers-logo.png" width="600"/>
<br>
<p>
<p align="center">
<img alt="Build" src="https://github.com/huggingface/tokenizers/workflows/Rust/badge.svg">
<a href="https://github.com/huggingface/tokenizers/blob/master/LICENSE">
<img alt="GitHub" src="https://img.shields.io/github/license/huggingface/tokenizers.svg?color=blue">
</a>
<a href="https://docs.rs/tokenizers/">
<img alt="Doc" src="https://docs.rs/tokenizers/badge.svg">
</a>
</p>
<br>

%package license
Summary: license components for the pypi-tokenizers package.
Group: Default

%description license
license components for the pypi-tokenizers package.


%package python
Summary: python components for the pypi-tokenizers package.
Group: Default
Requires: pypi-tokenizers-python3 = %{version}-%{release}

%description python
python components for the pypi-tokenizers package.


%package python3
Summary: python3 components for the pypi-tokenizers package.
Group: Default
Requires: python3-core
Provides: pypi(tokenizers)
Requires: pypi(huggingface_hub)

%description python3
python3 components for the pypi-tokenizers package.


%prep
%setup -q -n tokenizers-0.19.1
cd %{_builddir}
tar xf %{_sourcedir}/pypi-tokenizers-2024-06-03-18-08-43.tar.xz
cd %{_builddir}/tokenizers-0.19.1
mkdir -p ./vendor
cp -r %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/* %{_builddir}/tokenizers-0.19.1/./vendor

%build
## build_prepend content
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1717450587
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-tokenizers
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/aho-corasick/COPYING %{buildroot}/usr/share/package-licenses/pypi-tokenizers/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/aho-corasick/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/aho-corasick/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/anstream/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/anstream/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/anstyle-parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/anstyle-parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/64a8c11fd0f3068e743bfc681bcbef4f50a6b779 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/anstyle-query/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/anstyle-query/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/anstyle-wincon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/anstyle-wincon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/33dbd2d99ad231460bbb01812a52c85e577bd9ba || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/anstyle/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/anstyle/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f911b0506e6ba6a56b4edac717b461799f380ef0 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/base64/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/base64/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/bitflags-1.3.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/bitflags-1.3.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/colorchoice/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/colorchoice/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/console/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9a675655c0a9f0bb9c8109678651fe27bceaca04 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/crossbeam-deque/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/crossbeam-deque/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/crossbeam-epoch/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/crossbeam-epoch/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/darling/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/darling_core/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/darling_macro/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/cc1662c1ffded2451f1b822c62ec085862bd5816 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/derive_builder/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/derive_builder/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4c1c71430c0885114ef42fc256b803241cdcf898 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/derive_builder_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/derive_builder_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4c1c71430c0885114ef42fc256b803241cdcf898 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/derive_builder_macro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/derive_builder_macro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4c1c71430c0885114ef42fc256b803241cdcf898 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/either/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/either/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/encode_unicode/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/encode_unicode/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/188be4108decf997e0edd21c6dd83deaf320f255 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/env_filter/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/env_filter/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/env_logger/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/env_logger/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4dbe8833d0189c691b308c3dd40fab84ef2e9630 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/errno/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/errno/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/7a842f34e127456338641b14c7a00ec246d89fb6 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/esaxx-rs/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/fastrand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/fastrand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/fnv/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/fnv/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/getrandom/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/getrandom/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/c8eef3d34d69b1d62fd378fa02150a0bce62fd26 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/humantime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/humantime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ff432d95fdfee3587e45abd61685c2209d245901 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/ident_case/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/218fc8c15534e8840cbff5801582c450c97869ab || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/indicatif/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9a675655c0a9f0bb9c8109678651fe27bceaca04 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/instant/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/037192733999bccd7ed8d75123b7ec09feb4a12d || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/itertools-0.11.0/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/itertools-0.11.0/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/itertools/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/itertools/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/itoa/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/itoa/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/lazy_static/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/lazy_static/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/linux-raw-sys/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/linux-raw-sys/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/linux-raw-sys/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/macro_rules_attribute-proc_macro/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/60146279cd817681c6ff6d37b99abfdc979b2b32 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/macro_rules_attribute-proc_macro/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e055f1174d0221ea06972dc97b9d93afe08af1d || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/macro_rules_attribute/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/60146279cd817681c6ff6d37b99abfdc979b2b32 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/macro_rules_attribute/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e055f1174d0221ea06972dc97b9d93afe08af1d || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/matrixmultiply/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/matrixmultiply/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f6f1c63a464536513df4052c4851922ade5adfed || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/memchr/COPYING %{buildroot}/usr/share/package-licenses/pypi-tokenizers/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/memchr/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/memchr/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/minimal-lexical/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/minimal-lexical/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/minimal-lexical/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-tokenizers/cd3fe820606ed34ac2591caf068c7cabd3ab3509 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/monostate-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/monostate-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/monostate/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/monostate/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/ndarray/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/ndarray/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/70698c5cd94e53fcb69e4c61fc7e87d9f559c3fb || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/nom/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/27ea6989d4f34b7b944eb884410a31ae20d11686 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/num-complex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/num-complex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/num-integer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/num-integer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/num-traits/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/num-traits/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/onig/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f0e5967a26ecb154498e63518d58e923803cfbd5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/onig_sys/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-tokenizers/056be0a11583e26e88ede27601dff342dcaa07c5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/onig_sys/oniguruma/COPYING %{buildroot}/usr/share/package-licenses/pypi-tokenizers/061a5f18d5b7a5fe6a1da9419bef05b7d35f7cf6 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/paste/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/paste/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pkg-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pkg-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/portable-atomic/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/portable-atomic/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/ppv-lite86/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/088830dcb78eba1a2052df69bd5cba5445e8f2d7 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/ppv-lite86/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/e1c86f32641f01a5b85d6e9b20138e8470b883fc || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3-build-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3-build-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3-ffi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3-ffi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3-macros-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3-macros-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3-macros/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3/pyo3-runtime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/pyo3/pyo3-runtime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rand/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rand/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/4632a631b427f005d97734ea8c6a44090fec5cd9 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rand/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rand_chacha/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rand_chacha/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rand_chacha/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rand_core/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f14afa20edce530124d39cd56312c7781c19b267 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rand_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/d74ad13f1402c35008f22bc588a6b8199ed164d3 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rawpointer/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rawpointer/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/3a86cfdfa553511b381388859c9e94ce9e1f916b || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rayon-cond/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rayon-cond/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rayon-core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rayon-core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rayon/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rayon/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/regex-automata/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/regex-automata/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/regex-syntax/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/regex-syntax/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/regex-syntax/src/unicode_tables/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/68d12a03b339648117165b9c021b93f26974d6f6 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/regex/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/regex/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rustc-hash/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rustc-hash/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rustix/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rustix/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/rustix/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/ryu/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/ryu/LICENSE-BOOST %{buildroot}/usr/share/package-licenses/pypi-tokenizers/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/serde/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/serde/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/serde_derive/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/serde_derive/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/serde_json/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/serde_json/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/spm_precompiled/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/strsim/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f5feee4154156527645a9b18ef29da23fc859ca9 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/tempfile/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/tempfile/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/70693ba8757c4a17af68e39ab32e4e0d4a389416 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/thiserror-impl/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/thiserror-impl/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/thiserror/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/thiserror/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-normalization-alignments/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-normalization-alignments/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-normalization-alignments/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-segmentation/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-segmentation/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-segmentation/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-width/COPYRIGHT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5ed53061419caf64f84d064f3641392a2a10fa7f || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-width/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode-width/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode_categories/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unicode_categories/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/d27ef3ee8c433e848ca41075d018a1ad707e3c49 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/utf8parse/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/utf8parse/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/93074692b8a28bef1743c44a9e5b97b1401c0d09 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-tokenizers/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows-targets-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows-targets-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_aarch64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_aarch64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_aarch64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_aarch64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_i686_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_i686_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_i686_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_i686_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-tokenizers-2024-06-03-18-08-43/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/tokenizers-%{version}/tokenizers/LICENSE %{buildroot}/usr/share/package-licenses/pypi-tokenizers/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-tokenizers/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/pypi-tokenizers/037192733999bccd7ed8d75123b7ec09feb4a12d
/usr/share/package-licenses/pypi-tokenizers/056be0a11583e26e88ede27601dff342dcaa07c5
/usr/share/package-licenses/pypi-tokenizers/061a5f18d5b7a5fe6a1da9419bef05b7d35f7cf6
/usr/share/package-licenses/pypi-tokenizers/088830dcb78eba1a2052df69bd5cba5445e8f2d7
/usr/share/package-licenses/pypi-tokenizers/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/pypi-tokenizers/188be4108decf997e0edd21c6dd83deaf320f255
/usr/share/package-licenses/pypi-tokenizers/218fc8c15534e8840cbff5801582c450c97869ab
/usr/share/package-licenses/pypi-tokenizers/27ea6989d4f34b7b944eb884410a31ae20d11686
/usr/share/package-licenses/pypi-tokenizers/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/pypi-tokenizers/2bf5cac862d5a0480b5d5bcd3a1852d68bfeee84
/usr/share/package-licenses/pypi-tokenizers/33dbd2d99ad231460bbb01812a52c85e577bd9ba
/usr/share/package-licenses/pypi-tokenizers/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-tokenizers/3a86cfdfa553511b381388859c9e94ce9e1f916b
/usr/share/package-licenses/pypi-tokenizers/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-tokenizers/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/pypi-tokenizers/4632a631b427f005d97734ea8c6a44090fec5cd9
/usr/share/package-licenses/pypi-tokenizers/4c1c71430c0885114ef42fc256b803241cdcf898
/usr/share/package-licenses/pypi-tokenizers/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/pypi-tokenizers/4dbe8833d0189c691b308c3dd40fab84ef2e9630
/usr/share/package-licenses/pypi-tokenizers/50121d8b8c9f6483fe17ea679f28f85fe59b2a5a
/usr/share/package-licenses/pypi-tokenizers/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-tokenizers/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/pypi-tokenizers/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/pypi-tokenizers/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/pypi-tokenizers/5ed53061419caf64f84d064f3641392a2a10fa7f
/usr/share/package-licenses/pypi-tokenizers/5feaf15b3fa7d2d226d811e5fcd49098a1ea520c
/usr/share/package-licenses/pypi-tokenizers/60146279cd817681c6ff6d37b99abfdc979b2b32
/usr/share/package-licenses/pypi-tokenizers/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/pypi-tokenizers/64a8c11fd0f3068e743bfc681bcbef4f50a6b779
/usr/share/package-licenses/pypi-tokenizers/669a1e53b9dd9df3474300d3d959bb85bad75945
/usr/share/package-licenses/pypi-tokenizers/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/pypi-tokenizers/68d12a03b339648117165b9c021b93f26974d6f6
/usr/share/package-licenses/pypi-tokenizers/6e055f1174d0221ea06972dc97b9d93afe08af1d
/usr/share/package-licenses/pypi-tokenizers/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-tokenizers/70693ba8757c4a17af68e39ab32e4e0d4a389416
/usr/share/package-licenses/pypi-tokenizers/70698c5cd94e53fcb69e4c61fc7e87d9f559c3fb
/usr/share/package-licenses/pypi-tokenizers/7a842f34e127456338641b14c7a00ec246d89fb6
/usr/share/package-licenses/pypi-tokenizers/7df059597099bb7dcf25d2a9aedfaf4465f72d8d
/usr/share/package-licenses/pypi-tokenizers/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/pypi-tokenizers/93074692b8a28bef1743c44a9e5b97b1401c0d09
/usr/share/package-licenses/pypi-tokenizers/959ce149b1615b8bff3437f59282396756987859
/usr/share/package-licenses/pypi-tokenizers/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/pypi-tokenizers/9a675655c0a9f0bb9c8109678651fe27bceaca04
/usr/share/package-licenses/pypi-tokenizers/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/pypi-tokenizers/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/pypi-tokenizers/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/pypi-tokenizers/b716916e6b0b96af5ecadf1eaee25f966f5d6cb2
/usr/share/package-licenses/pypi-tokenizers/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/pypi-tokenizers/c8eef3d34d69b1d62fd378fa02150a0bce62fd26
/usr/share/package-licenses/pypi-tokenizers/cc1662c1ffded2451f1b822c62ec085862bd5816
/usr/share/package-licenses/pypi-tokenizers/cd3fe820606ed34ac2591caf068c7cabd3ab3509
/usr/share/package-licenses/pypi-tokenizers/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-tokenizers/d27ef3ee8c433e848ca41075d018a1ad707e3c49
/usr/share/package-licenses/pypi-tokenizers/d74ad13f1402c35008f22bc588a6b8199ed164d3
/usr/share/package-licenses/pypi-tokenizers/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/pypi-tokenizers/e1c86f32641f01a5b85d6e9b20138e8470b883fc
/usr/share/package-licenses/pypi-tokenizers/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/pypi-tokenizers/e9b475b5dccf14bd66d72dd12a04db75eaad1a9e
/usr/share/package-licenses/pypi-tokenizers/f0e5967a26ecb154498e63518d58e923803cfbd5
/usr/share/package-licenses/pypi-tokenizers/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-tokenizers/f14afa20edce530124d39cd56312c7781c19b267
/usr/share/package-licenses/pypi-tokenizers/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/pypi-tokenizers/f5feee4154156527645a9b18ef29da23fc859ca9
/usr/share/package-licenses/pypi-tokenizers/f6f1c63a464536513df4052c4851922ade5adfed
/usr/share/package-licenses/pypi-tokenizers/f911b0506e6ba6a56b4edac717b461799f380ef0
/usr/share/package-licenses/pypi-tokenizers/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85
/usr/share/package-licenses/pypi-tokenizers/ff432d95fdfee3587e45abd61685c2209d245901

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
